trigger: none # trigger = pipeline kab chalega

pool: # pool = pipeline kaha chalega
 name: demo_agent_pool

stages: # pipeline me kya chize/ commands chalegi
  - stage: buildPipeline
    jobs:
      - job: buildJob
        steps:
        - task: NodeTool@0
          displayName: node_tool_install
          inputs:
            versionSource: 'spec'
            versionSpec: '16.x'
        
        - task: Npm@1
          displayName: npm install
          inputs:
            command: 'install'
            workingDir: '$(System.DefaultWorkingDirectory)'
        
        - task: Npm@1
          displayName: npm run build
          inputs:
            command: 'custom'
            workingDir: '$(System.DefaultWorkingDirectory)'
            customCommand: 'run build'

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)/build'
            ArtifactName: 'drop'
            publishLocation: 'Container'

  - stage: deploy
    jobs:
      - job: 
        steps:
        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.ArtifactsDirectory)'
            cleanDestinationFolder: true
        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: '$(System.ArtifactsDirectory)'
            includeRootFolder: true
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            replaceExistingArchive: true

        - task: AzureWebApp@1
          inputs:
            azureSubscription: 'azureconnect'
            appType: 'webAppLinux'
            appName: 
            package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            runtimeStack: 'NODE|22-lts'